version: '3'
      
volumes:   
  pg_data2:
  static_volume:
  media:
    
services:
  db:
    image: postgres:13
    volumes:
      - pg_data2:/var/lib/postgresql/data
  backend:
    image: good8815585/kittygram_backend	
    env_file: .env
    volumes:   
      - static_volume:/backend_static
      - media:/media
  frontend:
    env_file: .env
    image: good8815585/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: good8815585/kittygram_nginx
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
      - media:/media
    ports:
      - 9000:80
